### ISSUE TITLE
Running in batch script

### ISSUE THREAD

**Issue by padovanas** [Andy-B-123/TargetSiteDuplicationFinder#1]
Hi Andy-B-123,

I would like to run this software on multiple samples simultaneously. I am trying to use this script:

module load python

in=$(sed -n ${SLURM_ARRAY_TASK_ID}p /path/to/files/RG.txt)

out=${in%_out.bam}-TSD 

echo $in
echo $out

python3 /path/to/scripts/TargetSiteDuplicationFinder/TSD_parser.cluster_wrapped.py --input_bam $in --output_base $out --cluster_identifer_path /path/to/software/cluster_identifier

As a test I ran it on 2 samples and got the following error for both:
/path/to/files/Sample1.bam
/path/to/files/Sample1.bam-TSD
ic| input_path_bam: '/path/to/files/Sample1.bam'
ic| output_base: '/path/to/files/Sample1.bam-TSD'
ic| input_bam_type: 'SR'
ic| cluster_identifer_path: '/path/to/software/cluster_identifier'
ic| len(bam_file_parameters): 998
ic| 'Short read sample indicated'
ic| tsv_file: <_io.TextIOWrapper name='/path/to/files/Sample1.bam_cluster_identifier.out-sort.cluster_identifier.out-marked.cluster_identifier.out-RG.cluster_identifier.out' mode='r' encoding='UTF-8'>
ic| tsv_reader: <_csv.reader object at 0x155542e4deb0>
ic| len(cluster_identifier_file_TSD_coordinates): 0
ic| cluster_identifier_file_TSD_coordinates: []
ic| len(bam_file_coordinates): 0
ic| len(bam_file_coordinates): 0
Custom path for 'cluster_identifer' from SCRAMBLE provided, checking...
'cluster_identifier' present. Proceeding...

 

0it [00:00, ?it/s]
0it [00:00, ?it/s]

Can you please advise me whether the TargetSiteDuplicationFinder can be used in a parallel batch script and how to solve this error?

Thanks,
AP

**Comment by Andy-B-123** [comment]
Hi AP, great question! Ah my mistake, the program generates an intermediate file which is not uniquely named and so running this in parallel is going to get messy. 

I've updated the script to make unique files based on the 'output_base' parameter, please try using the latest commit (424c7f4) which should help fix your issue!
